# Generated by Django 6.0.3 on 2026-03-28 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome_perfil', models.CharField(max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id_permissao', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome_permissao', models.CharField(max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=25)),
                ('descricao', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=15)),
                ('ano', models.IntegerField()),
                ('km_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perfil')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permissao')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('siape', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_servidor', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSev',
            fields=[
                ('id_sev', models.SmallAutoField(primary_key=True, serialize=False)),
                ('origem', models.CharField(max_length=25)),
                ('data_inicio', models.DateTimeField()),
                ('km_inicio', models.IntegerField()),
                ('destino', models.CharField(max_length=25)),
                ('data_fim', models.DateTimeField()),
                ('km_fim', models.IntegerField()),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servidor')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
        ),
    ]
