# Generated by Django 6.0.3 on 2026-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosev',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=12),
        ),
        migrations.AddField(
            model_name='servidor',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('EM_USO', 'Em uso'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=15),
        ),
    ]
