# Generated by Django 6.0.3 on 2026-05-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registrosev_status_servidor_status_veiculo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosev',
            name='local_dest',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
        ),
        migrations.AddField(
            model_name='registrosev',
            name='local_ori',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
        ),
    ]
