# Generated by Django 6.0.3 on 2026-05-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registrosev_local_dest_registrosev_local_ori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosev',
            name='data_fim',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registrosev',
            name='km_fim',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registrosev',
            name='local_dest',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrosev',
            name='local_ori',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
