# Generated by Django 6.0.3 on 2026-05-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_registrosev_data_fim_alter_registrosev_km_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosev',
            name='data_fim',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='registrosev',
            name='km_fim',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='registrosev',
            name='local_dest',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
