# Generated by Django 6.0.3 on 2026-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_registrosev_data_fim_alter_registrosev_km_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosev',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
