# Generated by Django 6.0.3 on 2026-05-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_registrosev_motivo_cancelamento'),
        ('app', '0006_seed_perfis_permissoes'),
    ]

    operations = [
    ]
