# Generated by Django 6.0.3 on 2026-06-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20260530_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('FISCALIZACAO', 'Fiscalização'), ('MANUTENCAO', 'Manutenção'), ('LOGISTICA', 'Logística'), ('LEVANTAMENTO', 'Levantamento'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10),
        ),
    ]
